name: "Terrahaxs Workflow"
on:
  workflow_dispatch:
    inputs:
      payload:
        required: true
        description: Runner Payload
      signature:
        required: true
        description: Signature of runner request signed by private Terrahaxs key
      logLevel:
        description: 'Log level'
        default: 'INFO'
jobs:
  terrahaxs:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    name: Terrahaxs Action
    container: terrahaxs/worker:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run Terrahaxs Action
      run: python /var/task/main.py
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
        LOG_LEVEL: ${{ github.event.inputs.logLevel }}
        PAYLOAD: ${{ github.event.inputs.payload }}
